# Generated by Django 4.1 on 2023-08-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advert", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="advertisement", table="advertisements",),
    ]
