# Generated by Django 4.1 on 2023-08-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advert", "0003_advertisement_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="image",
            field=models.ImageField(
                default="", upload_to="Django_projango/", verbose_name="Изображение"
            ),
            preserve_default=False,
        ),
    ]
